#!/usr/bin/python3

import curses
from curses import wrapper

def main(stdscr):
    # Clear screen
    stdscr.clear()

    stdscr.keypad(True)
    curses.cbreak()

    curses.start_color()
    curses.init_color(250, 400, 400, 400)
    curses.init_color(251, 600, 800, 600)
    curses.init_color(252, 800, 600, 600)

    stdscr.addstr(0, 0, "                     ", curses.A_REVERSE)
    curses.init_pair(1, curses.COLOR_MAGENTA, curses.COLOR_BLACK)    
    curses.init_pair(2, curses.COLOR_RED, curses.COLOR_BLACK)
    curses.init_pair(3, curses.COLOR_CYAN, curses.COLOR_BLACK)
    curses.init_pair(4, curses.COLOR_BLACK, 250)
    curses.init_pair(5, curses.COLOR_BLACK, 251)
    curses.init_pair(6, curses.COLOR_BLACK, 252)

    stdscr.addstr(2, 1, "   off   ", curses.color_pair(4))
    stdscr.addstr(3, 1, "   off   ", curses.color_pair(4))
    stdscr.addstr(4, 1, "   on    ", curses.color_pair(5))
    stdscr.addstr(5, 1, "  broken ", curses.color_pair(6))
    stdscr.addstr(6, 1, "   off   ", curses.color_pair(4))
    stdscr.addstr(7, 1, "   off   ", curses.color_pair(4))

    stdscr.addstr(2, 11, "   off   ", curses.color_pair(4))
    stdscr.addstr(3, 11, "   on    ", curses.color_pair(5))
    stdscr.addstr(4, 11, "   off   ", curses.color_pair(4))
    stdscr.addstr(5, 11, "  broken ", curses.color_pair(6))
    stdscr.addstr(6, 11, "   off   ", curses.color_pair(4))
    stdscr.addstr(7, 11, "   off   ", curses.color_pair(4))

    stdscr.refresh()
    stdscr.refresh()
    stdscr.getkey()

wrapper(main)

